name:                beehive
version:             0.1.0.0
github:              "jimd1989/beehive"
license:             BSD3
author:              "Jim Dalrymple"
maintainer:          "example@example.com"
copyright:           "2021 Jim Dalrymple"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/beehive#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- http-types
- protolude
- text
- unordered-containers
- wai
- warp

library:
  source-dirs:
    - src
  ghc-options:
    - -O2
    - -Wincomplete-patterns

default-extensions:
- GeneralizedNewtypeDeriving
- NamedFieldPuns
- NoImplicitPrelude
- OverloadedStrings
- RecordWildCards
- UnicodeSyntax

executables:
  beehive-exe:
    main:                Main.hs
    source-dirs:
      - app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wincomplete-patterns
    dependencies:
    - beehive

tests:
  beehive-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - beehive
